//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRentalApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEStatePurpos
    {
        public RealEStatePurpos()
        {
            this.RealEStates = new HashSet<RealEState>();
        }
    
        public byte PurposeID { get; set; }
        public string PurposeName { get; set; }
    
        public virtual ICollection<RealEState> RealEStates { get; set; }
    }
}
