//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRentalApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEStatesCity
    {
        public RealEStatesCity()
        {
            this.RealEstatesDistricts = new HashSet<RealEstatesDistrict>();
        }
    
        public byte CityID { get; set; }
        public string CityName { get; set; }
    
        public virtual ICollection<RealEstatesDistrict> RealEstatesDistricts { get; set; }
    }
}
