//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRentalApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEstatesDistrict
    {
        public RealEstatesDistrict()
        {
            this.CustomersFavorites = new HashSet<CustomersFavorite>();
            this.RealEStates = new HashSet<RealEState>();
        }
    
        public int DistrictID { get; set; }
        public string DistrictName { get; set; }
        public byte CityID { get; set; }
    
        public virtual ICollection<CustomersFavorite> CustomersFavorites { get; set; }
        public virtual ICollection<RealEState> RealEStates { get; set; }
        public virtual RealEStatesCity RealEStatesCity { get; set; }
    }
}
