//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRentalApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEstateComment
    {
        public int CommentID { get; set; }
        public string CommentTitle { get; set; }
        public string CommentContent { get; set; }
        public System.DateTime CommentDate { get; set; }
        public long RealEstateID { get; set; }
        public string Username { get; set; }
        public bool IsSpam { get; set; }
    
        public virtual RealEState RealEState { get; set; }
    }
}
