//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRentalApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResidentialRealEstate
    {
        public long RealEstateID { get; set; }
        public int RoomsNo { get; set; }
        public int BathsNo { get; set; }
        public bool WithGarden { get; set; }
        public bool WithRoof { get; set; }
        public Nullable<int> LevelNo { get; set; }
        public Nullable<int> HouseNo { get; set; }
    
        public virtual RealEState RealEState { get; set; }
    }
}
